### ISSUE TITLE
Incompatability issues with Traffic++

### ISSUE THREAD

**Issue by seiggy** [seiggy/Skylines-Traffic-Manager#3]
Not working with traffic++ timed lights go negative
Manual control does nothing even on a new map

**Comment by Thyariol** [comment]
Can confirm, that Timed Traffic Lights don't work and go negative.

**Comment by seiggy** [comment]
Thyariol, any way you can upload a save game? Either I've fixed the problem, or I just can't replicate it with my saves. Also, a mod list would be helpful.

**Comment by Thyariol** [comment]
Sure, i'll do that today!

**Comment by oczkers** [comment]
"Clear traffic" also does nothing for me (traffic++ with no despawn enabled)

**Comment by Thyariol** [comment]
Ok, here’s the state of things with my Skylines-Games. 

I normally use all of the following mods. I sorted them in terms of relevance (in my opinion) for TMPlus.

## Shouldn’t be relevant:

Automatic Bulldoze
No More Purple
First Person Camera
Traffic Report Tool
Extended Building Information Mod
One-Way Street Arrows
Better Budget
Tree Brush 
All Areas purchaseable

## Maybe relevant:

Terraform Tool
Road Color Changer
No Pillars

## Definitely relevant:

Improved Public Transport
Traffic++
Advanced Vehicle Options
Traffic manager (of course!)  

First i tested this savegame (http://steamcommunity.com/sharedfiles/filedetails/?id=482585416) with all Mods enabled. Here's what i noticed:
• Toggle Traffic Lights works
• Priority Signs seem to work, but it the cims stay way too long till they start driving
• Manual Traffic Lights seem to work fine
• Timed Traffic Lights work! (Your last update helped, it seems)
• Add/remove Crosswak work
• Clear Traffic work

Change Lanes and Disable despawning shouldn’t be shown, because i run Traffic++, which normally overwrites these two points. I only use lane changing with T++, but if there are no compatibility issues, never mind. 

So, at the moment it seems, that TM is working again as intended. Till now, i have not found any incompatibilites with T++ or other Mods i use. I’ll keep that monitored. 

Reloading the savegame several times did not break anything till now. 

Very, very nice!

**Comment by seiggy** [comment]
Hooray! So first patch will probably focus on fixing the priority system. Timings seem off there.

**Comment by seiggy** [comment]
Latest patch should have this issue resolved. All existing reproducible test cases I have are fixed at least.
